'Alliluya'
Morzhiha/calculater pull request #1
Opened 2019-07-31 08:11 UTC by Morzhiha

2019-07-31 08:57 UTC, Intellcet requested changes
В целом особо ничего не изменилось. Добавились файлики - это хорошо))

Что я хочу увидеть:

- Выраженную структуру калькулятора

- Выроженный интерфейс калькулятора

- ООП

2019-08-01 04:54 UTC, Intellcet requested changes
Помимо всего прочего, необходимо добавить в корень приложения файл `.gitignore`, в котором указываются файлы и папки, которые гит должен игнорировать во время коммита. В этом файле нужно указать папки `__pycache__` и `.idea`

2019-08-01 04:54 UTC, Intellcet commented on calc/calculate.py
> +    def calc(self, a, b, d):
Это метод должен быть вынесен из этого класса. Класс _Calculator_ - это структура данных. Здесь ты описываешь структуру (какие свойства имеет, что умеет делать). В данном случае, класс Calculator не имеет никаких полей и умеет складывать, вычитать, умножать и делить, при том делить он должен с проверкой на нуль второго числа

2019-08-01 04:54 UTC, Intellcet commented on calc/calculate.py
> +            try:
Неоправданное использование блока *try-except*. Почему просто не написать
`if b != 0:`
  `return div(a, b)`
`return 'На ноль делить нельзя!'`?

2019-08-01 04:54 UTC, Intellcet commented on calc/calculate.py
> +        if d == '+':
На самом деле громоздкая запись. Я бы упростил. Подумай как этого можно добиться

2019-08-01 04:54 UTC, Intellcet commented on service.py
>  def init():
Если функция называется *init* то она должна что-то инициализировать. Я не вижу никакой инициализации.
Также, это не сервис -> некорректное название файла. Надо переименовать. В этом файле ты так или иначе рисуешь менюшку калькулятора. Лучше назвать что-то типа menuBaseCalc. Нет ООП. Переписать на ООП.

2019-08-01 04:54 UTC, Intellcet commented on service.py
> +    print('{} {} {} = {}'.format(a, d, b, calculator.calc(a, b, d)))
Плохо и считывать данные с консоли, и дергать функцию калькулятора, и выводить обратно на консоль в одной функции.
Разбить на несколько

2019-08-01 04:54 UTC, Intellcet commented on service.py
>  def again():
Не очень классное название... В принципе, эта функция так нужна? Нельзя как-то реализовать этот функционал по-другому, не вынося это в отдельную функцию?

2019-08-01 04:54 UTC, Intellcet commented on service.py
>      b = int(input('Второе число '))
Рассмотрим такой сценарий действий: Я хочу умножить 3 на 5, я ввожу *3*, затем я думаю "три надо умножить...", а вместо знака умножения меня просят ввести второе число. Непорядок, надо исправить

2019-08-01 04:54 UTC, Intellcet commented on calc/calculate.py
> +            print('Неизвестная операция')
Это надо бы выводить раньше, на моменте, когда пользователь ввел операцию. Также не помешает проверка на то, числа ли вообще пришли или нет. Притом, проверки такие должны быть сразу после ввода. Также, должна быть возможность повторного ввода, в случае неверного.

2019-08-02 04:54 UTC, Intellcet requested changes

2019-08-02 04:54 UTC, Intellcet commented on .gitignore
> +/calc/__pycache__
слеш указывать не надо. Просто `.idea`, `__pycache__` и т.д.

2019-08-02 04:54 UTC, Intellcet commented on .gitignore
> +/calc/__pycache__
Он же не сработал, видишь файлы остались

2019-08-02 04:54 UTC, Intellcet commented on calc/calculate.py
> +
Стоит изменить название файла, чтобы соответствовал названию класса

2019-08-02 04:54 UTC, Intellcet commented on menuBaseCalc.py
> +calculator = Calculator()
Это нужно делать в конструкторе класса `MenuBaseCalc`

2019-08-02 04:54 UTC, Intellcet commented on menuBaseCalc.py
> +        a, d, b = s
Сложнааа, что за запись? Объясни мне

2019-08-02 04:54 UTC, Intellcet commented on menuBaseCalc.py
> +        operatorList = {'+': calculator.sum(a, b), '-': calculator.sub(a, b),
Это лучше сделать полем класса и обозначить как константу

2019-08-02 04:54 UTC, Intellcet commented on menuBaseCalc.py
> +        while d not in ('+' , '-', '*', '/'):
Не смутило, что ты делаешь две одинаковые проверки по разному в двух разных функциях?)
Здесь и в `getResult` две одинаковые по существу проверки, сделанные по-разному

2019-08-02 04:54 UTC, Intellcet commented on menuBaseCalc.py
> +            a = int(input('Некорректный формат данных! Введите ещё раз первое число '))
Делаешь одно и то же несколько раз в этой функции. Может, есть смысл вынеси это в отдельную функцию, куда бы отправлялось то, что ввел пользователь, а функция проверяла бы на то, валидные данные или нет

2019-08-02 04:54 UTC, Intellcet commented on menuBaseCalc.py
> +        d = input('Введите одно из действий: +, -, *, /: ')
Допустим для чисел переменные `a` и `b` я понять могу, но действие зачем называть `d`? Почему нельзя назвать _operator_ или _action_?

2019-08-02 04:54 UTC, Intellcet commented on menuBaseCalc.py
> +        if d == '/':
Тоже лучше вынести в отдельную функцию

2019-08-02 04:54 UTC, Intellcet commented on menuBaseCalc.py
> +        return int(a), d, int(b)
Здесь приведение типов не нужно. Ты выше везде это уже делаешь, здесь не может быть ничего кроме числа

2019-08-02 04:54 UTC, Intellcet commented on menuBaseCalc.py
> +        return int(a), d, int(b)
Также, что за возврат такой странный? Объясни

2019-08-02 04:54 UTC, Intellcet commented on menuBaseCalc.py
> +        if d in operatorList.keys():
Здесь эта проверка избыточна. У тебя всегда вызывается `getResult` после ввода, где ты уже проверяла является ли d корректным оператором. Можно просто возвращать `return operatorList[d]`

2019-08-02 04:54 UTC, Intellcet commented on menuBaseCalc.py
> +        else:
Это никогда не сработает

2019-08-02 04:54 UTC, Intellcet commented on menuBaseCalc.py
> +            return operatorList[d]
**operatorsList**, а не operatorList

2019-08-02 05:58 UTC, Morzhiha commented on menuBaseCalc.py
> +        else:
Работает вообще-то

2019-08-02 07:47 UTC, Intellcet commented on menuBaseCalc.py
> +        else:
Как у тебя может сработать ветка `else`, если эта функция всегда вызывается после того, как идентичная проверка уже была произведена в той функции, где ты вызываешь эту? Следовательно здесь всегда будет корректный оператор. Если не веришь - отдебажь или принтами посмотри

2019-08-02 09:18 UTC, Intellcet requested changes

2019-08-02 09:18 UTC, Intellcet commented on calc/calculator.py
> +            return 0
Лучше вернуть сразу строку, что делить на нуль нельзя

2019-08-02 09:18 UTC, Intellcet commented on menuBaseCalc.py
> +        while operator not in ('+', '-', '*', '/'):
Ну ведь это тоже можно вынести в отдельную функцию по аналогии с операндами

2019-08-02 09:18 UTC, Intellcet commented on menuBaseCalc.py
> +        if operator == '/':
Снова одна и та же проверка в двух местах. Что в калькуляторе, что тут. Предлагаю выпилить такую проверку из калькулятора, обернуть это в функцию и здесь её вызывать

2019-08-02 09:18 UTC, Intellcet commented on menuBaseCalc.py
> +        return int(a), operator, int(b)
Я бы всё-таки возвращал кортежем, ну да ладно...
Приводить типы здесь **не надо**, убери

2019-08-02 09:18 UTC, Intellcet commented on menuBaseCalc.py
> +        print(operatorsList)
Не убрала ненужный принт

2019-08-02 09:18 UTC, Intellcet commented on menuBaseCalc.py
> +        operatorsList = {'+': self.calculator.sum(a, b), '-': self.calculator.sub(a, b),
Просил сделать это в виде константы на уровне класса...

2019-08-02 09:21 UTC, Morzhiha commented on calc/calculator.py
> +            return 0
проблема в operatorsList(там сразу считает все действия), поэтому делаю доп условие здесь(например 1 + 0 выдаст ошибку)

2019-08-02 09:23 UTC, Morzhiha commented on menuBaseCalc.py
> +        return int(a), operator, int(b)
это забыла убрать

2019-08-02 09:28 UTC, Morzhiha commented on menuBaseCalc.py
> +        operatorsList = {'+': self.calculator.sum(a, b), '-': self.calculator.sub(a, b),
если засунуть в конструктор в виде константы, откуда брать значения a и b?

2019-08-02 09:30 UTC, Intellcet commented on menuBaseCalc.py
> +        operatorsList = {'+': self.calculator.sum(a, b), '-': self.calculator.sub(a, b),
У тебя в кортеже должны быть _ссылки_ на функции, а не результат их выполнения

2019-08-02 09:31 UTC, Intellcet commented on calc/calculator.py
> +            return 0
Потому что operatorsList **не должен** считать, он должен хранить ссылки на нужные функции

2019-08-02 10:05 UTC, Intellcet requested changes

2019-08-02 10:05 UTC, Intellcet commented on menuBaseCalc.py
> +        self.operatorsList = {'+': self.calculator.sum, '-': self.calculator.sub,
Не переименовала в methodsList... Мы же всё-таки храним методы, а операторы - просто ключи к ним...

2019-08-02 10:05 UTC, Intellcet commented on menuBaseCalc.py
> +        if operator == '/':
В функцию так и не обернула

2019-08-02 10:05 UTC, Intellcet commented on menuBaseCalc.py
> +        while operator not in ('+', '-', '*', '/'):
Насколько я помню, у кортежей есть классный метод **keys()**, который возвращает тебе список ключей кортежа, Лучше уж написать так: `while operator not in self.operatorsList.keys()`. Вероятность ошибки меньше в 2 раза. Потому что вдруг тебе захочется добавить пятое действие, тогда надо будет добавлять в 2 места, а так в одно - operatorsList

2019-08-02 19:27 UTC, Intellcet reviewed
Мержу

2019-08-02 19:27 UTC, merged