create new complexCalc
Morzhiha/calculater pull request #2
Opened 2019-08-03 19:44 UTC by Morzhiha

2019-08-04 06:08 UTC, Intellcet requested changes

2019-08-04 06:08 UTC, Intellcet commented on calc/complexCalc.py
> +        return ComplexNumber(z1.getRe() + z2.getRe(), z1.getIm() + z2.getIm())
Вместо обычных "+", "-", "*", "/" нужно использовать методы базового калькулятор, переопределенные в комплексном

2019-08-04 06:08 UTC, Intellcet commented on calc/complexCalc.py
>  class ComplexCalc(MenuBaseCalc):
Не смущает, что у тебя класс "Комплексный калькулятор" наследуется от "МенюБазовогоКлалькулятора"?

2019-08-04 06:08 UTC, Intellcet commented on calc/complexCalc.py
> +        print('({}+{}i) {} ({}+{}i) = {}'.format(z1.getRe(), z1.getIm(), operator, z2.getRe(), z2.getIm(),
А если число вида "2-3i"? Тогда запись будет "2+-3i", надо переделать в "2-3i".

2019-08-04 06:08 UTC, Intellcet commented on calc/complexCalc.py
>          while not str(num1).isdigit() and str(num2).isdigit():
А если я неверно ввел только одну часть числа? Например "фыв" и "3". Мне снова 3 вводить? Не хорошо это...

2019-08-04 06:08 UTC, Intellcet commented on calc/complexCalc.py
> +        return '(' + str(z.getRe()) + '+' + str(z.getIm()) + 'i)'
По-хорошему комплекное число должно уметь само себя представлять в виде строки (нужно переопределить метод toString(в питоне называется по-другому, погугли))

2019-08-04 06:08 UTC, Intellcet commented on calc/complexCalc.py
> +class ComplexNumber:
Все классы в одном файле?!?!?!?! о_О
Разбить на файлы!

2019-08-04 20:10 UTC, Intellcet requested changes

2019-08-04 20:10 UTC, Intellcet commented on calc/complexCalc.py
> +from calc.complexNumber import ComplexNumber
В папочке _calc_ должны быть только калькуляторы, исходя из названия. ComplexNumber лучше вынести в отдельную папку - _struct_ (сокращение от structure)

2019-08-04 20:10 UTC, Intellcet commented on calc/complexCalc.py
>  class MethodsComplexCalc:
Ну может всё-таки это и есть ComplexCalc, а не MethodsComplexCalc?

2019-08-04 20:10 UTC, Intellcet commented on calc/complexCalc.py
> +        return ComplexNumber(self.calculator.sum(z1.getRe(),z2.getRe()), self.calculator.sum(z1.getIm(), z2.getIm()))
Хочу наследование в классе увидеть + использование методов родителя через _super()_

2019-08-04 20:10 UTC, Intellcet commented on calc/complexCalc.py
> +        print(a)
Забыла убрать ненужный принт

2019-08-04 20:10 UTC, Intellcet commented on calc/complexNumber.py
> +        if self.getIm() < 0:
В качестве тернарного оператора это нельзя написать?

2019-08-04 20:10 UTC, Intellcet commented on menu/menuComplexCalc.py
> +        b = input('Введите мнимую часть второго числа ')
А здесь нет проверок на корректный ввод данных. К тому же, у тебя дублирование кода. Надо вынести

2019-08-04 20:10 UTC, Intellcet commented on menu/menuComplexCalc.py
> +            num1, num2 = input('Некорректный формат данных! Введите ещё раз действительную и мнимую части ').split()
Опять-таки, если я введу "sad" и 3, мне снова придется вводить 3. Не есть хорошо. Надо бы исправить

2019-08-04 20:10 UTC, Intellcet commented on menu/menuComplexCalc.py
> +        return z
Здесь нет смысла создавать переменную, можно сразу возвращать результат функции

2019-08-05 06:11 UTC, Morzhiha commented on calc/complexNumber.py
> +        if self.getIm() < 0:
это громоздко и неудобно

2019-08-05 14:54 UTC, Intellcet requested changes

2019-08-05 14:54 UTC, Intellcet commented on calc/complexNumber.py
> +        if self.getIm() < 0:
То есть сейчас - громоздко и неудобно. Много if-ов, нужно разбираться что когда как

2019-08-05 14:54 UTC, Intellcet commented on calc/complexCalc.py
> +        print(z2.getRe())
Принт не убрала

2019-08-05 14:54 UTC, Intellcet commented on menu/menuBaseCalc.py
>              b = input('Делить на ноль нельзя! Введите ещё раз второе число ')
Но я же могу ввести строку)

2019-08-05 14:54 UTC, Intellcet commented on menu/menuComplexCalc.py
> +        self.methodsComplex = ComplexCalc()
Почему комплексный калькулятор запоминается в переменную "комплексные методы"?

2019-08-05 14:54 UTC, Intellcet commented on menu/menuComplexCalc.py
> +            b = self.divisionByZero(b)
Откуда эти функции? Из класса-родителя? Тогда через `super()` вызывай

2019-08-05 14:54 UTC, Intellcet commented on menu/menuComplexCalc.py
> +        z2 = self.isComplexNumber(a, b)
Эти проверки так необходимы? Ты и без того делаешь проверку на то, число `a` и `b` или нет. Здесь эта проверка явно избыточна (или там где проверяешь по отдельности `a` и `b`)

2019-08-05 14:54 UTC, Intellcet commented on menu/menuComplexCalc.py
> +            num2 = input('Некорректный формат данных! Введите ещё раз мнимую часть ')
В случае, если я введу `2` и `sad` мне заново придется вводить `2`. Не хочу так. Хочу только `sad` ввести заново

2019-08-05 20:06 UTC, Morzhiha commented on menu/menuComplexCalc.py
> +        z2 = self.isComplexNumber(a, b)
Ну при делении знаменатнль не равен 0 должен быть же... Вот и должны одновременно не равны 0

2019-08-05 20:06 UTC, Morzhiha commented on menu/menuComplexCalc.py
> +        z2 = self.isComplexNumber(a, b)
Ну при делении знаменатнль не равен 0 должен быть же... Вот и должны одновременно не равны 0

2019-08-05 20:38 UTC, Morzhiha commented on calc/complexNumber.py
> +        if self.getIm() < 0:
Во-первых ,нельзя использовать с elif,
Во-вторых, строка получается длинной слишком

2019-08-06 04:03 UTC, Intellcet requested changes

2019-08-06 04:03 UTC, Intellcet commented on menu/menuComplexCalc.py
> +            a = self.isNumber(self.divisionByZero(a))
`self.isNumber`, надо изменить на `super().isNumber`

2019-08-06 04:03 UTC, Intellcet commented on structure/complexNumber.py
> +        z = '(' + str(self.getRe()) + str(self.getIm()) + 'i' + ')' if self.getIm() < 0 else '(' + str(self.getRe()) + ')' \
А зачем эти скобочки вокруг числа? Они ж явно не нужны

2019-08-06 04:03 UTC, Intellcet commented on menu/menuComplexCalc.py
> +        b = super().isNumber(b)
Мне не нравится что эти 4 строки отличаются от строк 35-38 только словом в строке "первого"/"второго". Может стоит это вынести в отдельную функцию и вызывать здесь 2 раза - для первого числа и второго?

2019-08-06 04:08 UTC, Intellcet commented on menu/menuComplexCalc.py
> +            a = self.isNumber(self.divisionByZero(a))
Аналогично для divisionByZero.

А почему он будет просить ввести второе число два раза? Ах да, потому что эта функция предполагала работу с обычными числами и вызывается дважды))))

Что мешает её переопределить для работы с комплексными числами?

2019-08-06 19:03 UTC, Morzhiha commented on structure/complexNumber.py
> +        z = '(' + str(self.getRe()) + str(self.getIm()) + 'i' + ')' if self.getIm() < 0 else '(' + str(self.getRe()) + ')' \
так читабельнее

2019-08-06 19:30 UTC, Intellcet commented on structure/complexNumber.py
> +        z = '(' + str(self.getRe()) + str(self.getIm()) + 'i' + ')' if self.getIm() < 0 else '(' + str(self.getRe()) + ')' \
Дискуссионно. Из-за них у тебя и усложняется конкатенация строки

2019-08-07 05:49 UTC, Intellcet requested changes

2019-08-07 05:49 UTC, Intellcet commented on menu/menuBaseCalc.py
> +            self.answer(self.getInputData())
Вызываешь функцию, а объявляешь её ниже

2019-08-07 05:49 UTC, Intellcet commented on menu/menuComplexCalc.py
> +            z = self.inputComplex()
вызываешь функцию, а объявляешь её ниже

2019-08-07 05:49 UTC, Intellcet commented on menu/menuComplexCalc.py
> +        print('{} {} {} = {}'.format(z1, operator, z2, self.getResult(z1, operator, z2)))
вызываешь функцию, а объявляешь её ниже

2019-08-07 06:16 UTC, Intellcet approved these changes

2019-08-07 06:17 UTC, merged